### ISSUE TITLE
not running on xcode 9

### ISSUE THREAD

**Issue by oschanger** [Qusic/TraceUtility#17] opened 2017-09-26 06:51 UTC
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/xk/wgkkgbt178l6b7kg6ybwlm3r0000gn/T/main-adba15.m
clang: note: diagnostic msg: /var/folders/xk/wgkkgbt178l6b7kg6ybwlm3r0000gn/T/main-adba15.cache
clang: note: diagnostic msg: /var/folders/xk/wgkkgbt178l6b7kg6ybwlm3r0000gn/T/main-adba15.sh
clang: note: diagnostic msg: /var/folders/xk/wgkkgbt178l6b7kg6ybwlm3r0000gn/T/main-adba15.crash
clang: note: diagnostic msg: 

********************

**Comment by oschanger** [comment] 2017-09-27 03:27
It's a LLVM 9.0 bug. I'm using LLVM 8.0 's clang complier in XcodeDefault.xctoolchain.And it can compile now.But  still have some other problems.

**Comment by pixuan** [comment] 2017-09-29 02:42
@oschanger I meet with the same problem, I've tried to comment code which's below TUPrint(@"Trace: %@\n", tracePath). This time compile is success, but it throwes out "Can't discover the application's bundle path" exception, it seems wrong with bundle path for Instruments plugins and packages.
@Qusic The code seems broken on Xcode9, how to fix it?

**Comment by oschanger** [comment] 2017-09-29 02:49
@pixuan simply add this TUPrint(@"Trace: %@\n", tracePath) seems does't work for compile?Which line did you add.   I've tried to fix PFLoadPlugin() problem. But fails

**Comment by pixuan** [comment] 2017-09-29 03:25
@oschanger  I comment all the code below this, not add it. The compile error may be caused by them.
I what to solve the problem step by step.

**Comment by oschanger** [comment] 2017-09-29 04:25
@pixuan i comment this line but not work

**Comment by oschanger** [comment] 2017-09-29 06:30
this works ...

**Comment by oschanger** [comment] 2017-09-29 06:30
@pixuan this works ...

**Comment by Aozorany** [comment] 2017-09-29 10:19
It may caused by the 'flattenTree' block in [instrumentID isEqualToString:@"com.apple.xray.instrument-type.coresampler2"] condition, I commented all code in this condition and no error appears.

**Comment by oschanger** [comment] 2017-09-30 02:01
@Aozorany  PFTLoadPlugins() yeah  but still have PFTLoadPlugins() problem

**Comment by oschanger** [comment] 2017-09-30 02:01
@Aozorany yeah but still have PFTLoadPlugins() problem

**Comment by one2zero** [comment] 2017-10-25 09:32
@oschanger change bundle path can fix PFTLoadPlugins() crash
`[NSBundle bundleWithPath:@"/Applications/Xcode.app/Contents/Applications/Instruments.app"]`

but PFTTraceDocument still catch an error ，as same as use Instrument.app(8.3) to open the trace file
`Error Domain=Supported Capability Problem Code=0 "Missing features" UserInfo={NSLocalizedDescription=Missing features, NSLocalizedRecoverySuggestion=This document was saved by a newer version of Instruments and the file format has significantly changed.  The document will need to be opened by the newer version.
, XRCapabilityRangesKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {9223372036854775807, 0}";
}, XRRequiredVersionsKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {1, 1}";
}, NSLocalizedFailureReason=Forward compatibility checks have failed.}
`

seems 9.0 has different way to load trace file

**Comment by hotkidfamily** [comment] 2017-10-25 23:12
this problem is same to me.

**Comment by noshuai** [comment] 2017-11-02 10:17
也是遇到了同样问题.  使用Xcode9编译, trace是iOS11.0的手机生成的. 

Error: Error Domain=Supported Capability Problem Code=0 "Missing features" UserInfo={NSLocalizedDescription=Missing features, NSLocalizedRecoverySuggestion=This document was saved by a newer version of Instruments and the file format has significantly changed.  The document will need to be opened by the newer version.
, XRCapabilityRangesKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {9223372036854775807, 0}";
}, XRRequiredVersionsKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {1, 1}";
}, NSLocalizedFailureReason=Forward compatibility checks have failed.}

**Comment by MarStarck** [comment] 2017-11-09 08:23
@one2zero I add the bundle path but when loading plugin it will fail to load optimized model XRPackageModel 9.0.omo. Maybe this model is changed.


Update: this warning is instruments problem. it is no harm.

**Comment by MarStarck** [comment] 2017-12-01 07:35
I don't know how the author digged out  the PFTLoadPlugins function. class-dump cannnot find it.
In my study, xcode 9 need to load more package other than plugin, but I cannot find the function to load packages.

**Comment by oschanger** [comment] 2017-12-01 07:51
@MarStarck This function is in Instruments.app  -->  InstrumentsPlugIn.framework

**Comment by MarStarck** [comment] 2017-12-01 08:12
@oschanger How you find it?

**Comment by oschanger** [comment] 2017-12-01 08:51
@MarStarck cause this logic should be in Instruments.app   
so I recursively class-dump every framework in it and grep

**Comment by MarStarck** [comment] 2017-12-01 09:17
but my class-dump result doesn't contain this function, my reposite is https://github.com/MarStarck/xcode_instrument_headers
I use `class-dump -H` command

**Comment by oschanger** [comment] 2017-12-01 09:36
@MarStarck 


#!/bin/bash

# Run this with:
# find /Applications/Xcode.app/ -type f -perm -100 -exec ./extract.sh '{}' \;
# Afterwords run: (to remove all empty directories)
# find . -d -type d -empty -exec rmdir {} \;

APP=$1
BASE_DIR=`pwd`

OUTPUT=$(file "$APP")
if [[ $OUTPUT == *Mach-O* ]]; then
  TARGET_DIR=$BASE_DIR"/"$APP
  mkdir -p "$TARGET_DIR"
  class-dump -H -o "$TARGET_DIR" "$APP" > /dev/null
  nm -g -U -j "$APP" > "$TARGET_DIR"/exported_symbols.h
fi

**Comment by oschanger** [comment] 2017-12-01 09:40
```
#!/bin/bash

# Run this with:
# find /Applications/Xcode.app/ -type f -perm -100 -exec ./extract.sh '{}' \;
# Afterwords run: (to remove all empty directories)
# find . -d -type d -empty -exec rmdir {} \;

APP=$1
BASE_DIR=`pwd`

OUTPUT=$(file "$APP")
if [[ $OUTPUT == *Mach-O* ]]; then
  TARGET_DIR=$BASE_DIR"/"$APP
  mkdir -p "$TARGET_DIR"
  class-dump -H -o "$TARGET_DIR" "$APP" > /dev/null
  nm -g -U -j "$APP" > "$TARGET_DIR"/exported_symbols.h
fi

```

**Comment by oschanger** [comment] 2017-12-01 09:40
@MarStarck 
```
#!/bin/bash

# Run this with:
# find /Applications/Xcode.app/ -type f -perm -100 -exec ./extract.sh '{}' \;
# Afterwords run: (to remove all empty directories)
# find . -d -type d -empty -exec rmdir {} \;

APP=$1
BASE_DIR=`pwd`

OUTPUT=$(file "$APP")
if [[ $OUTPUT == *Mach-O* ]]; then
  TARGET_DIR=$BASE_DIR"/"$APP
  mkdir -p "$TARGET_DIR"
  class-dump -H -o "$TARGET_DIR" "$APP" > /dev/null
  nm -g -U -j "$APP" > "$TARGET_DIR"/exported_symbols.h
fi
```

**Comment by MarStarck** [comment] 2017-12-04 07:58
I have figure it out. Just adding InstrumentsPackaging into your project is enough.
btw, I cannot change compiler to LLVM 8.0, you know how can I install it?

**Comment by oschanger** [comment] 2017-12-04 08:48
@MarStarck 
I've tired to add InstrumentsPackaging.framework to "Link Binary With Libraries", but didn't work.
How did you do it?

**Comment by MarStarck** [comment] 2017-12-04 08:55
try go to /Instruments.app/Contents/Packages/
and install .instrdst files

**Comment by oschanger** [comment] 2017-12-04 11:16
@MarStarck 
Cool, it works!     
Why you need LLVM8? I changed it before by replacing clang compiler in Xcode9 with the one in Xcode8

**Comment by MarStarck** [comment] 2017-12-04 11:25
because I met the same compile error as you used to in LLVM 9 when compile flattenTree function.

**Comment by oschanger** [comment] 2017-12-04 11:27
I remember use LLVM8 will meet same version problem as Xcode8

**Comment by oschanger** [comment] 2017-12-04 11:43
new trace grabbed by xcode will report
```
2017-12-04 19:41:45.607648+0800 TraceUtility[91420:4712423] Cleaned up abandoned user-installed distribution lock
2017-12-04 19:41:45.607885+0800 TraceUtility[91420:4712423] Cleaned up abandoned user-installed distribution lock
2017-12-04 19:41:45.894098+0800 TraceUtility[91420:4712423] Month 13 is out of bounds
Error: Error Domain=Supported Capability Problem Code=0 "Missing features" UserInfo={NSLocalizedDescription=Missing features, NSLocalizedRecoverySuggestion=This document was saved by a newer version of Instruments and the file format has significantly changed.  The document will need to be opened by the newer version.
, XRCapabilityRangesKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {9223372036854775807, 0}";
}, XRRequiredVersionsKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {1, 1}";
}, NSLocalizedFailureReason=Forward compatibility checks have failed.}
Program ended with exit code: 1
```
older trace is ok

**Comment by oschanger** [comment] 2017-12-04 11:43
new trace grabbed by xcode9 will report
```
2017-12-04 19:41:45.607648+0800 TraceUtility[91420:4712423] Cleaned up abandoned user-installed distribution lock
2017-12-04 19:41:45.607885+0800 TraceUtility[91420:4712423] Cleaned up abandoned user-installed distribution lock
2017-12-04 19:41:45.894098+0800 TraceUtility[91420:4712423] Month 13 is out of bounds
Error: Error Domain=Supported Capability Problem Code=0 "Missing features" UserInfo={NSLocalizedDescription=Missing features, NSLocalizedRecoverySuggestion=This document was saved by a newer version of Instruments and the file format has significantly changed.  The document will need to be opened by the newer version.
, XRCapabilityRangesKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {9223372036854775807, 0}";
}, XRRequiredVersionsKey={
    "com.apple.dt.instruments.track_pinning" = "NSRange: {1, 1}";
}, NSLocalizedFailureReason=Forward compatibility checks have failed.}
Program ended with exit code: 1
```
older trace is ok

**Comment by MarStarck** [comment] 2017-12-06 08:14
@oschanger can you share your dumped .h files?  I met lots of exceptions when using class-dump...
There must be something wrong during the initialization.

**Comment by oschanger** [comment] 2017-12-07 07:36
@MarStarck 
Your email?

**Comment by HussainMehdi** [comment] 2017-12-07 08:36
@oschanger I need that dumped h too for traceUtility. (hussainmehdi03@gmail.com)

**Comment by MarStarck** [comment] 2017-12-07 08:51
@oschanger <difei_coder@163.com> Thx!
btw, I've found if you delete open.creq in .trace, then you can open it.

**Comment by oschanger** [comment] 2017-12-18 08:48
@MarStarck   how did you find to delete .creq?

**Comment by oschanger** [comment] 2017-12-18 09:16
Summary:
1.change path in main.m
```
static NSBundle *NSBundle_mainBundle_replaced(id self, SEL _cmd) {
    //return [NSBundle bundleWithIdentifier:@"com.apple.dt.Instruments"];
    return [NSBundle bundleWithPath:@"/Applications/Xcode.app/Contents/Applications/Instruments.app"];
}
```
2.comment all code in if block:
`       if ([instrumentID isEqualToString:@"com.apple.xray.instrument-type.coresampler2"]) 
`
3.install packages in
`/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Packages
`
4.delete .creq file in .trace

**Comment by oschanger** [comment] 2017-12-18 10:33
Summary:
1.change path in main.m
```
static NSBundle *NSBundle_mainBundle_replaced(id self, SEL _cmd) {
    //return [NSBundle bundleWithIdentifier:@"com.apple.dt.Instruments"];
    return [NSBundle bundleWithPath:@"/Applications/Xcode.app/Contents/Applications/Instruments.app"];
}
```
2.comment all code in if block:
`if ([instrumentID isEqualToString:@"com.apple.xray.instrument-type.coresampler2"])
`
3.install packages in
`/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Packages
`
4.delete .creq file in .trace

**Comment by skaldic** [comment] 2018-01-02 10:25
The same error: 

> FAILURE Error: Error Domain=Supported Capability Problem Code=0 "Missing features" UserInfo={NSLocalizedDescription=Missing features, NSLocalizedRecoverySuggestion=This document was saved by a newer version of Instruments and the file format has significantly changed.  The document will need to be opened by the newer version.
> , XRCapabilityRangesKey={
>     "com.apple.dt.instruments.track_pinning" = "NSRange: {9223372036854775807, 0}";
> }, XRRequiredVersionsKey={
>     "com.apple.dt.instruments.track_pinning" = "NSRange: {1, 1}";
> }, NSLocalizedFailureReason=Forward compatibility checks have failed.} 

is given also by Instruments, if you try to open a 9.x trace file with the older 8.3.3 Instruments app.
It must be the way they open the new documents. Instead of this:

`PFTTraceDocument *document = [[PFTTraceDocument alloc] initWithContentsOfURL:[NSURL fileURLWithPath:tracePath] ofType:@"Trace Document" error:&error];` we should use something different.

Any ideas?

I don't want to delete the .creq file as trace files have backwards compatibility (e.g. opening a 8.3.3 trace in 9.x Instruments) I think they have an internal check: if creq = 9.0 use the new PFTTraceDocument otherwise use the old one.

**Comment by vivianali** [comment] 2018-02-02 02:00
@oschanger I have meet the same problem: PFTTraceDocument still catch an error ，as same as use Instrument.app(8.3) to open the trace file
Error Domain=Supported Capability Problem Code=0 "Missing features" UserInfo={NSLocalizedDescription=Missing features, NSLocalizedRecoverySuggestion=This document was saved by a newer version of Instruments and the file format has significantly changed. The document will need to be opened by the newer version. , XRCapabilityRangesKey={ "com.apple.dt.instruments.track_pinning" = "NSRange: {9223372036854775807, 0}"; }, XRRequiredVersionsKey={ "com.apple.dt.instruments.track_pinning" = "NSRange: {1, 1}"; }, NSLocalizedFailureReason=Forward compatibility checks have failed.}
Have you fix it? How to fix the problem?

**Comment by MonkyQ** [comment] 2018-02-24 08:18
Sadly !When I update to Xcode 9.2 PFTTraceDocument have not init.
`PFTTraceDocument *document = [[PFTTraceDocument alloc]initWithContentsOfURL:[NSURL fileURLWithPath:tracePath] ofType:@"Trace Document" error:&error];`
Console
`Error: Error Domain=Instruments Plug-in Error Code=-6 "Document Missing Template Error" UserInfo={NSLocalizedDescription=Document Missing Template Error}`
How to do bros!

**Comment by Qusic** [comment] 2018-04-02 11:10
crash with xcode 9.2 fixed in https://github.com/Qusic/TraceUtility/commit/98648d9d82940efab8f713c147bbcd1abfc4ce90#diff-0cad19250ae08acbc7488724c19cf9e9R34

**Closed as completed by Qusic** 2018-04-02 11:10 UTC
