### ISSUE TITLE
new core animation fps tool

### ISSUE THREAD

**Issue by eughermann** [Qusic/TraceUtility#29] opened 2018-06-26 18:18 UTC
Hi there.
Apple is doing a great job un-discovering document formats from people.
In new Instruments 'com.apple.xray.instrument-type.coreanimation' tool was deprecated and replaced with 'com.apple.dt.coreanimation-fps'
New instrument does not contain XRVideoCardRun objects, only base XRRun with metadata.
Introspection didn't give positive results to me. I walked through all available ivars, unpacked NSData buffers, but I don't see where actual numbers are.

Any ideas?

**Comment by Qusic** [comment] 2018-06-27 03:05
duplicate of #28

**Closed as completed by Qusic** 2018-06-27 03:05 UTC

**Comment by Qusic** [comment] 2018-06-29 08:51
fixed in 88ef512f62b0883866a6e673beae32cac841ced6
